### PR TITLE
show 0 sat fee on failed payments; general fixes; move out shared css…

### LINKED ISSUE #132: TransactionDetails: show 0 mSat fee with failed payments
currently it just shows "mSat" without an amount

image

If the lightning payment failed, show 0 msat fee instead of empty

### PR DESCRIPTION
**Pull request by cstenglein**
Closes #132 

This fixes:
- the Unit enum (showed 0 / 1 instead of the string)
- moved css for detials into extra file instead of variables
- show 0 mSat fee on failed payments
- moved "wallet locked" string into translation file

### CODE REVIEW

File: src/components/Home/TransactionCard/TransactionDetailModal/LNDetails/LNDetails.tsx [hunk 1]
```diff
@@ -30,44 +29,40 @@ export const LNDetails: FC<LNDetailProps> = (props) => {
 
   return (
     <section className="flex flex-col py-3 my-4">
-      <article className={containerClasses}>
-        <h6 className={keyClasses}>{t("tx.txid")}</h6>
-        <p className={valueClasses}>{details.id}</p>
+      <article className="detail-container">
```
Comment (escapedcat) [inline src/components/Home/TransactionCard/TransactionDetailModal/LNDetails/LNDetails.tsx:32]: Wondering if this could be a component (with its CSS) and coudl be used in both places

**Review by escapedcat — APPROVED** [review]

**Comment by escapedcat** [comment]
Wanna add a test for showing 0?

File: src/components/Home/TransactionCard/TransactionDetailModal/LNDetails/LNDetails.tsx (hunk 1 above)
Comment (cstenglein) [reply src/components/Home/TransactionCard/TransactionDetailModal/LNDetails/LNDetails.tsx:32]: Great idea!

**Comment by cstenglein** [comment]
> Wanna add a test for showing 0?

Don't know if necessary since it shows up immediately and don't think we play around with the unit all the time.
