### PR TITLE
fix invoice expiration

### LINKED ISSUE #373: Expiry LND & CLN difference
See https://github.com/fusion44/blitz_api/issues/129

### PR DESCRIPTION
**Pull request by cstenglein**
fixes #373

### CODE REVIEW

File: backend-mock/lightning.js [hunk 1]
```diff
@@ -77,9 +84,53 @@ router.get("/decode-pay-req", (req, res) => {
             },
           },
         ],
+        currency: "",
       })
     );
   }, 1500);
+
+  // CLN invoice
```
Comment (escapedcat) [inline backend-mock/lightning.js:92]: What's this?

Comment (cstenglein) [reply backend-mock/lightning.js:92]: Created an invoice with c-lightning to check if any fields differ.
