### PR TITLE
fix image carousel alignment on big screens

### LINKED ISSUE #185: (AppInfo): Fix image arrows on big screens
The arrows to move to the next / previous image are not aligned to the image and could move outside the image.

### PR DESCRIPTION
**Pull request by cstenglein**
Fixes #185 

image

### CODE REVIEW

File: src/components/Apps/AppInfo/AppInfo.tsx [hunk 1]
```diff
@@ -28,6 +33,7 @@ export const AppInfo: FC<AppInfoProps> = (props) => {
       })
       .catch((_) => {
         // use fallback icon if image for id doesn't exist
+        // TODO: error handling
```
Comment (escapedcat) [inline src/components/Apps/AppInfo/AppInfo.tsx:36]: In the future we could add a link to an existing issue to `TODO`s.  
Helps to tackle all usages later on when that ticket is being worked on.

**Review by escapedcat — APPROVED** [review]

File: src/components/Apps/AppInfo/AppInfo.tsx (hunk 1 above)
Comment (cstenglein) [reply src/components/Apps/AppInfo/AppInfo.tsx:36]: Good idea!
