### PR TITLE
Error handling, design fixes

### LINKED ISSUE #15: HTTP Error Handling
Currently there is **no** error handling for all web requests at all (for some just catching without any action).

This could result in a broken app when there is a other status code than 200 (e.g. not authenticated) and could confuse users when no notification etc. happens.

- [ ] When token was expired and no action was done before (refreshing with action done in #146), then log out automatically or on 401
- [ ] on everything except 200 and 401 error code show error dialog and forward the message from the backend (for now)

### LINKED ISSUE #238: add error handling for "wrong" lightning invoice
If you write "lnbc11111" in the lightning invoice in the send modal, you can submit it & get a 500 from the backend, but now it's stuck in the modal.

### PR DESCRIPTION
**Pull request by cstenglein**
Merge after #266 

closes #15  
closes #238

### CODE REVIEW

File: src/components/Shared/ReceiveModal/ReceiveModal.tsx [hunk 1]
```diff
@@ -35,23 +35,33 @@ const ReceiveModal: FC<Props> = ({ onClose }) => {
...
-      setIsLoading(false);
+      await instance
+        .post("lightning/new-address", {
+          type: "p2wkh",
+        })
+        .then((resp) => {
+          setAddress(resp.data);
+        })
+        .catch((err) => {
+          setError(`${t("login.error")}: ${err.response?.data?.detail}`);
```
Comment (escapedcat) [inline src/components/Shared/ReceiveModal/ReceiveModal.tsx:60]: Receive modal is using `login.error`? Is this intended or just a same needed word?

File: src/components/Shared/ReceiveModal/ReceiveModal.tsx [hunk 2]
```diff
@@ -162,6 +178,8 @@ const ReceiveModal: FC<Props> = ({ onClose }) => {
             </div>
           )}
 
+          {error && <div className="my-4 text-red-500">{error}</div>}
```
Comment (escapedcat) [inline src/components/Shared/ReceiveModal/ReceiveModal.tsx:181]: Should this be an error component because it's used in the same way in other places?

File: src/components/Shared/ReceiveModal/ReceiveModal.tsx (hunk 1 above)
Comment (cstenglein) [reply src/components/Shared/ReceiveModal/ReceiveModal.tsx:60]: Same needed word. 
Translates to `An error occured`

Will move some translations to a more "common" parent, but currently just need to get finished :)

File: src/components/Shared/ReceiveModal/ReceiveModal.tsx (hunk 2 above)
Comment (cstenglein) [reply src/components/Shared/ReceiveModal/ReceiveModal.tsx:181]: Good idea! :+1:

File: src/components/Shared/ReceiveModal/ReceiveModal.tsx (hunk 1 above)
Comment (cstenglein) [reply src/components/Shared/ReceiveModal/ReceiveModal.tsx:60]: Created a issue #268

File: src/components/Shared/SendModal/SendLN/SendLN.test.tsx [hunk 3]
```diff
@@ -27,20 +28,16 @@ describe("SendLN", () => {
...
     setup();
     const invoiceInput = await screen.findByLabelText("wallet.invoice");
 
-    expect(
-      await screen.findByRole("button", { name: "wallet.send" })
-    ).not.toBeDisabled();
+    expect(await screen.findByText("wallet.send")).not.toBeDisabled();
 
-    userEvent.click(await screen.findByRole("button", { name: "wallet.send" }));
+    userEvent.click(await screen.findByText("wallet.send"));
```
Comment (escapedcat) [inline src/components/Shared/SendModal/SendLN/SendLN.test.tsx:40]: Just a prefrenence or a reason?

Comment (cstenglein) [reply src/components/Shared/SendModal/SendLN/SendLN.test.tsx:40]: Tests were failing, so I changed that and it fixed it

Comment (cstenglein) [reply src/components/Shared/SendModal/SendLN/SendLN.test.tsx:40]: retried, yes the tests are failing when using findByRole. Most likely because there is now also an icon inside it, not only text and thus the name is not "wallet.send" anymore.
